name: Python CD

on:
  workflow_run:
    workflows: ["Python CI"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull bit3down/valentine:latest
    - name: Delete old container
      run: sudo docker rm -f valentine || true
    - name: Run Docker container
      run: sudo docker run -d --name valentine -p 80:80 bit3down/valentine:latest