name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Run tests
      run: |
        python -m unittest discover
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t bit3down/valentine:latest .

    - name: Push Docker image
      run: docker push bit3down/valentine:latest